# Generated by Django 4.2.7 on 2023-11-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specs', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
