# Generated by Django 4.2.7 on 2023-11-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_alter_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
